### PR TITLE
Use Markdown on closeness-sensing body text

### LINKED ISSUE #170: Cosmetic issue. Potential Markdown not interpreted correctly in My COVID Alerts card
Issue: 
Image from iOS
Syntax to make the text 'Note:' in bold is not interpreted.
Steps to reproduce: On iOS, turn OFF the bluetooth. Go to the My COVID Alerts tab.
Solution: ~~Sick & Destroy~~ Investigate & Solve

### PR DESCRIPTION
**Pull request by AlanSl**
Fixes https://github.com/project-vagabond/covid-green-app/issues/170

I've set all the closeness screens to use markdown for body text so it's easier to maintain: most don't use it currently but if a future text update changes that, it should just work.

### CODE REVIEW

File: src/components/molecules/closeness-sensing/active.tsx [hunk 1]
```diff
@@ -33,9 +34,9 @@ export const Active: FC<{onboarding?: boolean}> = ({onboarding = false}) => {
         {onboarding && (
           <>
             <Spacing s={20} />
-            <Text style={text.default}>
+            <Markdown style={text.default}>
```
Comment (floridemai) [inline src/components/molecules/closeness-sensing/active.tsx]: You don't need `style={text.default}` for the `Markdown` component. Hopefully it still works as it should.

**Review by floridemai — APPROVED** [review]
